name: React App Test and Deploy
on: [ push, workflow_dispatch ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Node Js Installation
        uses: actions/setup-node@v4
        with:
          node-version: 18.0
      - name: Install Dependencies
        run: npm install
      - name: Creating a Build
        run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 975049984328.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Creating and Pushing Docker Image
        run: | 
          docker build -t 975049984328.dkr.ecr.us-east-1.amazonaws.com/testimages:v1 .
          docker push 975049984328.dkr.ecr.us-east-1.amazonaws.com/testimages:v1
      - name: Update kube config
        run: aws eks update-kubeconfig --name raghaveks --region $AWS_REGION
